### PR TITLE
add myself as maintainer and bump to 8.2.1

### LINKED ISSUE #33: Two majors behind?
https://pypi.org/project/cheroot/#history v8.2.1 is out!

### PR DESCRIPTION
**Pull request by carlodri**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #33

### CODE REVIEW

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
@conda-forge/core can someone please merge this? @pmlandwehr AFAIK is mostly inactive on conda-forge since a long time, and I would like to un-block this feedstock

**Comment by jjhelmus** [comment]
@carlodri Thanks for being a maintainer on the feedstock.

**Pull request merged**
